# Generated by Django 5.1.5 on 2025-02-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='model_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
