# Generated by Django 5.1.5 on 2025-02-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chathistory_model_name_alter_chathistory_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
