# Generated by Django 5.1.5 on 2025-03-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
